# syntax=gcr.io/host-project-f966/dockerfile:1
# Build step
FROM gcr.io/host-project-f966/python-builder-base:v1 AS builder
WORKDIR /src

# TODO: Move this to another repo and place the model in a base image
RUN mkdir -p ./src/models/codes_model
# COPY build/pytorch_model.bin ./src/models/codes_model
COPY requirements.txt .

#   Set variables for python virtual env. https://pythonspeed.com/articles/activate-virtualenv-dockerfile/
ENV VIRTUAL_ENV=/src/.venv
ENV PATH="$VIRTUAL_ENV/bin:$PATH"
#   setup python virtual environment ad get packages
RUN rm -rf /src/.venv &&\
    pyvirtinit

          
ENV GOOGLE_APPLICATION_CREDENTIALS="${HOME}/.config/gcloud/application_default_credentials.json"
RUN --mount=type=secret,required=true,id=gcp-creds,target=$GOOGLE_APPLICATION_CREDENTIALS pip install --no-cache-dir -r /src/requirements.txt

COPY . /

